credentials:
  usernames:
    aweder:
      email: alex.weder14@gmail.com
      name: Alex Weder
      password: $2b$12$62fWKMASZhOfW4xDC5HX6OpBHsV6s4dQUwyh/942NjPqssCZh3AT. # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
